chats/urls.py
from django.urls import path
from chats.views import (
    IndexView,
    delete_view,
    chat_csv_view,
    chat_session_view,
    create_view,
    update_view,
)

app_name = "chats"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("csv/<int:pk>/", chat_csv_view, name="csv"),
    path("session/<int:pk>/", chat_session_view, name="chat"),
    path("create_with_file/", create_view, name="create"),
    path("update_with_file/<int:pk>/", update_view, name="update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('driver/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('documents/', include('documents.urls')),
    path('resumes/', include('resumes.urls')),
    path('chatter/', include('chats.urls')),
    path('urls/', include('urls.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documents/urls.py
from django.urls import path
from .views import index_view, document_interact_view, document_csv_view, delete_view
app_name = 'documents'

urlpatterns = [
    path('index/', index_view, name='index'),
    path('interact/<int:pk>/', document_interact_view, name='interact'),
    path('csv/<int:pk>/', document_csv_view, name='csv'),
    path('delete/<int:pk>/', delete_view, name='delete'), 
]

resumes/urls.py
from django.urls import path
from .views.index import index_view
from .views.delete_view import delete_cover_letter_view, delete_view
from .views.trigger_llm_and_list import trigger_and_list_view
from .views.create_cover import create_cover_view
from .views.update_description import update_description_view
from .views.edit_generated_text import edit_generated_text_view
from .views.view_pdf_as_html import pdf_as_html_view
from .views.view_pdf import pdf_view, pdf_download
from .views.user_job_profile import (
    user_job_profile_view,
    user_job_profile_pdf_view,
    user_job_profile_form_view
)
from .views.edit_cover_address_to import cover_address_view
from.views.list_job_covers import ListJobCovers


app_name = "resumes"

urlpatterns = [
    path("index/", index_view, name="index"),
    path("create/<int:pk>/", create_cover_view, name="create"),
    path("llm-and-list/<int:pk>/", trigger_and_list_view, name="trigger_and_list"),
    path(
        "update-description/<int:pk>/",
        update_description_view,
        name="update_description",
    ),
    path(
        "edit-generated-text/<int:pk>/",
        edit_generated_text_view,
        name="edit_generated_text",
    ),
    path("pdf-html/<int:pk>/", pdf_as_html_view, name="pdf_html"),
    path("cover-pdf/<int:pk>/", pdf_view, name="pdf_view"),
    path("download-pdf/<int:pk>/", pdf_download, name="pdf_download"),
    path("user-job-profile/<int:pk>/", user_job_profile_view, name="user_job_profile"),
    path("user-job-profile-form/<int:pk>/", user_job_profile_form_view, name="user_job_profile_form"),
    path("job-covers/<int:pk>/", ListJobCovers.as_view(), name="list_job_covers") ,
 
    path(
        "user-job-profile-pdf/<int:pk>/<int:id>/",
        user_job_profile_pdf_view,
        name="user_job_profile_pdf",
    ),
    path(
        "cover-address/<int:pk>/<int:pdf_key>/",
        cover_address_view,
        name="cover_address",
    ),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("delete-cover/<int:pk>/", delete_cover_letter_view, name="delete_cover"),
]

urls/urls.py
from django.urls import path
from urls.views import url_index_view, interaction_view, delete_view, url_csv_view

app_name='urls'
urlpatterns = [
    path('', url_index_view, name='index'),
    path('interactions/<int:pk>/', interaction_view, name='interactions'),

    path('csv/<int:pk>/', url_csv_view, name='csv'),
    path('delete/<int:pk>/', delete_view, name='delete'),

]

templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="px-4 py-5 my-5 text-center"> 
  <h1 class="display-5 fw-bold text-body-emphasis">{{ text.text_7|safe }}</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      {{ text.text_8|safe }}
    </p>
  </div>
</div>
<div class="container text-center">
  <div class="row">
    <div class="col"> 
      <a target="_blank" href="https://youtu.be/ouNGvIOp2us">
        <video width="320" height="240" autoplay loop muted>
          <source src="{% static 'videos/custom_chat.mp4' %}" type="video/mp4">
        </video>
      </a>
    </div>
    <div class="col">
      <a target="_blank" href="https://www.youtube.com/watch?v=MbGQLK119Bw">
        <video width="320" height="240" autoplay loop muted>
          <source src="{% static 'videos/cover_letter.mp4' %}" type="video/mp4">
        </video>
      </a>
    </div>
    <div class="col">
      <a target="_blank" href="https://youtu.be/a6p_NF4LNUo">
        <video width="320" height="240" autoplay loop muted>
          <source src="{% static 'videos/yt_vid.mp4' %}" type="video/mp4">
        </video>
      </a>
    </div>
  </div>
</div> 
<div class="container">
  {{ text.text_9|safe }}  
  {{text.text_3|safe}}

</div>

{% endblock content %}

templates/pages/private.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{{ text.text_5|safe }}
{% endblock content %}

templates/pages/profile.html
{% extends 'base.html' %}
{% block content%}
{% load crispy_forms_tags %}
{{user.email}}
<div class="row">
  <div class="col-md-4">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Documents</th>
          <th scope="col">Urls</th>
          <th scope="col">Chatters</th>
          <th scope="col">Resumes Uploaded</th>
          <th scope="col">Cover Letters Created</th>
        </tr>
      </thead>
      <tbody> 
        <tr>
          <th scope="row">
            <a href="{% url 'documents:index' %}">
              {{ documents.all.count }}
            </a>
          </th>
          <td><a href="{% url 'urls:index' %}">{{ urls.all.count }}</a></td>
          <td><a href="{% url 'chats:index' %}">{{ chats.all.count }}</a></td>
          <td><a href="{% url 'resumes:index' %}">{{ resumes.all.count }}</a></td>
          <td><a href="{% url 'resumes:list_job_covers' user.id %}">{{ cover_letters.all.count }}</a></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success btn-sm">Save</button> 
    </form>
    {{ text.text_4|safe }}
  </div>
</div>
{% endblock content %}