core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('driver/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('documents/', include('documents.urls')),
    path('resumes/', include('resumes.urls')),
    path('chatter/', include('chats.urls')),
    path('urls/', include('urls.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resumes/urls.py
from django.urls import path
from .views.index import index_view
from .views.delete_view import delete_cover_letter_view, delete_view
from .views.trigger_llm_and_list import trigger_and_list_view
from .views.create_cover import create_cover_view
from .views.update_description import update_description_view
from .views.edit_generated_text import edit_generated_text_view
from .views.view_pdf_as_html import pdf_as_html_view
from .views.view_pdf import pdf_view, pdf_download
from .views.user_job_profile import (
    user_job_profile_view,
    user_job_profile_pdf_view,
    user_job_profile_form_view
)
from .views.edit_cover_address_to import cover_address_view
from.views.list_job_covers import ListJobCovers


app_name = "resumes"

urlpatterns = [
    path("index/", index_view, name="index"),
    path("create/<int:pk>/", create_cover_view, name="create"),
    path("llm-and-list/<int:pk>/", trigger_and_list_view, name="trigger_and_list"),
    path(
        "update-description/<int:pk>/",
        update_description_view,
        name="update_description",
    ),
    path(
        "edit-generated-text/<int:pk>/",
        edit_generated_text_view,
        name="edit_generated_text",
    ),
    path("pdf-html/<int:pk>/", pdf_as_html_view, name="pdf_html"),
    path("cover-pdf/<int:pk>/", pdf_view, name="pdf_view"),
    path("download-pdf/<int:pk>/", pdf_download, name="pdf_download"),
    path("user-job-profile/<int:pk>/", user_job_profile_view, name="user_job_profile"),
    path("user-job-profile-form/<int:pk>/", user_job_profile_form_view, name="user_job_profile_form"),
    path("job-covers/<int:pk>/", ListJobCovers.as_view(), name="list_job_covers") ,
 
    path(
        "user-job-profile-pdf/<int:pk>/<int:id>/",
        user_job_profile_pdf_view,
        name="user_job_profile_pdf",
    ),
    path(
        "cover-address/<int:pk>/<int:pdf_key>/",
        cover_address_view,
        name="cover_address",
    ),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("delete-cover/<int:pk>/", delete_cover_letter_view, name="delete_cover"),
]

resumes/views/create_cover.py
from .libraries import *



@login_required
def create_cover_view(request, pk):
    user = request.user
    resume = Resume.objects.get(pk=pk)
    cover = CoverLetter.objects.order_by("-time").filter(resume_id=resume)
    text = Pagetext.objects.get(pk=1)
    form = CoverLetterForm(request.POST or None)
    context = {
        "form": form,
        "user": user,
        "cover": cover,
        "text": text,
        "resume": resume,
    }
    load_context = {
        "form": form,
        "user": user,
        "cover": cover,
        "text": text,
        "resume": resume,
    }
    if user != resume.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    if request.method == "POST":
        if form.is_valid():
            form.instance.resume_id = resume
            form.instance.user_id = request.user
            wait_to_save = form.save(commit=False)
            wait_to_save.save()
            messages.add_message(request, messages.INFO, "Job description created")
            # return render(request, "resumes/create_content.html", context)
            return HttpResponseRedirect(reverse("resumes:create", args=(resume.id,)))
        else:
            messages.add_message(request, messages.INFO, "Please complete all required fields to continue.")
            return render(request, "resumes/create.html", context)

    return render(request, "resumes/create.html", context=load_context)

resumes/views/delete_view.py
from .libraries import *

@login_required
def delete_view(request, pk):
    text = Pagetext.objects.get(pk=1)
    object = get_object_or_404(Resume, id=pk)
    context = {"object": object, "text": text}
    if request.user != object.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            object.delete()
            messages.add_message(request, messages.INFO, "Resume deleted")
            return redirect("resumes:index")

        return render(request, "resumes/delete.html", context)
    

@login_required
def delete_cover_letter_view(request, pk):
    text = Pagetext.objects.get(pk=1)
    object = get_object_or_404(CoverLetter, id=pk)
   
    context = {"object": object, "text": text}
    if request.user != object.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            object.delete()
            messages.add_message(request, messages.INFO, "Cover Letter deleted")
            return redirect("resumes:create", object.resume_id.id)

        return render(request, "resumes/delete.html", context)

resumes/views/edit_cover_address_to.py
from .libraries import *

@login_required
def cover_address_view(request, pk, pdf_key):
    user = request.user
    # resume = Resume.objects.get(pk=pk)
    cover = CoverLetter.objects.get(pk=pk)
    pdf = PdfContent.objects.get(id=pdf_key)
    text = Pagetext.objects.get(pk=1)

    form = EditCoverLetterForm(request.POST or None, instance=cover)
    context = {
        "form": form,
        "user": user,
        "cover": cover,
        "text": text,
        # "resume": resume,
        "pdf": pdf,
    }
    load_context = {
        "form": form,
        "user": user,
        "cover": cover,
        "text": text,
        # "resume": resume,
        "pdf": pdf,
    }
    if user != cover.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            if form.is_valid():
                # form.instance.resume_id = resume
                form.instance.user_id = request.user

                wait_to_save = form.save(commit=False)

                wait_to_save.save()

                messages.add_message(request, messages.INFO, "Job company/manager info updated.")
                return redirect("resumes:pdf_html", pdf.id)
            else:
                messages.add_message(
                    request,
                    messages.INFO,
                    "Please complete all required fields to continue.",
                )
                return render(request, "resumes/cover_address_form.html", context)

    return render(request, "resumes/cover_address_form.html", context=load_context)

resumes/views/edit_generated_text.py
from .libraries import *


@login_required
def edit_generated_text_view(request, pk):
    user = request.user

    pdf = PdfContent.objects.get(pk=pk)
    text = Pagetext.objects.get(pk=1)

    form = EditGeneratedTextForm(request.POST or None, instance=pdf)
    context = {"form": form, "user": user, "pdf": pdf, "text": text}
    load_context = {"form": form, "user": user, "pdf": pdf, "text": text}
    if user != pdf.user:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            if form.is_valid():
                form.instance.user_id = request.user
                wait_for_doctype = form.save(commit=False)
                wait_for_doctype.save()

                messages.add_message(
                    request, messages.INFO, "Job Cover Letter Content Updated!"
                )
                return redirect("resumes:pdf_html", pdf.id)

            else:
                return render(request, "edit_generated_text_form.html", context)

        return render(
            request, "resumes/edit_generated_text_form.html", context=load_context
        )

resumes/views/index.py
from .libraries import *


@login_required
def index_view(request):
    user = request.user
    if user.job_profile.full_name == "":
        messages.add_message(
            request, messages.INFO, "This needs to be completed before you continue!"
        )
        return redirect("resumes:user_job_profile", user.pk)

    user = request.user
    resumes = Resume.objects.order_by("-uploaded_on").filter(user_id=request.user)
    text = Pagetext.objects.get(pk=1)

    form = ResumeForm(request.POST, request.FILES)
    context = {"form": form, "user": user, "resumes": resumes, "text": text}
    load_context = {"user": user, "resumes": resumes, "text": text}
    if request.method == "POST":
        if form.is_valid():
            form.instance.user_id = request.user
            wait_for_doctype = form.save(commit=False)
            file_extension = pathlib.Path(str(wait_for_doctype.resume_path)).suffix

            if file_extension == ".txt" or file_extension == ".pdf":
                wait_for_doctype.save()
                messages.add_message(
                    request, messages.INFO, "Resume uploaded and ready to go!"
                )
                return redirect("resumes:index")
            else:
                messages.add_message(
                    request,
                    messages.INFO,
                    "Document type not supported, its gotta be a PDF.",
                )
                return redirect("resumes:index")
        else:
            form = ResumeForm()
            return render(request, "resumes/index.html", context)

    return render(request, "resumes/index.html", context=load_context)

resumes/views/libraries.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Resume, CoverLetter, PdfContent, UserJobProfile
from ..forms import (
    ResumeForm,
    CoverLetterForm,
    UserJobProfileForm,
    EditGeneratedTextForm,
    EditCoverLetterForm,
    UserJobProfileNameForm,
)
from pages.models import Pagetext
import pathlib
from ..functions import resume_cover_llm

import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from datetime import datetime

resumes/views/list_job_covers.py
from .libraries import *
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

class ListJobCovers(LoginRequiredMixin, ListView):
    paginate_by = 10 
    model = CoverLetter
    context_object_name = "covers"
    template_name = 'resumes/list_job_covers.html'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_id=self.request.user.id)

        return queryset 

resumes/views/trigger_llm_and_list.py
from .libraries import *
 
@login_required
def trigger_and_list_view(request, pk):
    print('we are here')    
    user = request.user
    cover = CoverLetter.objects.get(pk=pk)
    pdfs = PdfContent.objects.filter(cover_letter=cover)
    text = Pagetext.objects.get(pk=1)
    
    context = {
        "user": user,
        "cover": cover,
        "text": text,
        "pdfs": pdfs,

    }

    load_context = {
        "user": user,
        "cover": cover,
        "text": text,
        "pdfs": pdfs,

    }
    if user != cover.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    if request.method == "GET":
        return render(request, "resumes/trigger_and_list.html", context=load_context)
    


    if (
        request.method == "POST"
        or None
        and (
            request.POST.get("form_type") == "trigger_llm" 
        )
    ):
        
        try:
            # pass
            resume_cover_llm(
                            job_description=cover.description_text,
                            resume_url=cover.resume_id.resume_path.path,
                            trigger_text=text.char_19,
                            user=request.user,
                            cover_letter=cover
                        )
        except Exception as e:
            if e:
                messages.add_message(
                    request,
                    messages.INFO,
                    "An empty response was returned.  check your API key",
                )

            else:
                messages.add_message(request, messages.INFO, "Cover Letter Created!")
                return HttpResponseRedirect(reverse("resumes:trigger_and_list"))
        else:
            return render(request, "resumes/trigger_and_list.html", context)

    return render(request, "resumes/trigger_and_list.html", context=load_context)          

resumes/views/update_description.py
from .libraries import *


@login_required
def update_description_view(request, pk):
    user = request.user
    cover = CoverLetter.objects.get(pk=pk)
    text = Pagetext.objects.get(pk=1)
    form = CoverLetterForm(request.POST or None, instance=cover)
    context = {"form": form, "user": user, "cover": cover, "text": text}
    load_context = {"form": form, "user": user, "cover": cover, "text": text}
    if user != cover.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    # else:
    elif request.method == "POST":
        if form.is_valid():
            form.instance.user_id = request.user
            wait_to_save = form.save(commit=False)
            wait_to_save.save()
            print(wait_to_save.description_text)
            messages.add_message(request, messages.INFO, "Job Description Updated!")
            # return render(request, "resumes/create.html", context)
            return HttpResponseRedirect(
                reverse("resumes:trigger_and_list", args=(cover.id,))
            )
        else:
            return render(request, "resumes/form_template.html", context)

    return render(request, "resumes/form_template.html", context=load_context)

resumes/views/view_pdf.py
from .libraries import *


def pdf_view(request, pk):
    template_path = "resumes/view_pdf.html"
    # current date and time
    date = datetime.now().strftime("%B %d, %Y")
    pdf = PdfContent.objects.get(pk=pk)
    text = Pagetext.objects.get(pk=1)
    user_job_info = UserJobProfile.objects.get(user=request.user)
    user = request.user

    context = {
        "pdf": pdf,
        "text": text,
        "user": user,
        "company_name": pdf.cover_letter.company_name,
        "hiring_manager_info": pdf.cover_letter.content,
        "user_job_info": user_job_info,
        "date": date,
    }
    file_name = (f"{user_job_info.full_name}_{pdf.cover_letter.company_name}.pdf")
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = f'filename="{file_name}"'
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
        return HttpResponse("We had some errors <pre>" + html + "</pre>")
    return response


def pdf_download(request, pk):
    template_path = "resumes/pdf_download.html"
    # current date and time
    date = datetime.now().strftime("%B %d, %Y")
    pdf = PdfContent.objects.get(pk=pk)
    text = Pagetext.objects.get(pk=1)
    user_job_info = UserJobProfile.objects.get(user=request.user)
    user = request.user

    context = {
        "pdf": pdf,
        "text": text,
        "user": user,
        "company_name": pdf.cover_letter.company_name,
        "hiring_manager_info": pdf.cover_letter.content,
        "user_job_info": user_job_info,
        "date": date,
    }
    file_name = (f"{user_job_info.full_name}_{pdf.cover_letter.company_name}.pdf")
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type="application/pdf")
    # response["Content-Disposition"] = 'filename="report.pdf"'
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
        return HttpResponse("We had some errors <pre>" + html + "</pre>")
    return response

resumes/views/view_pdf_as_html.py
from .libraries import *


def pdf_as_html_view(request, pk):
    date = datetime.now().strftime("%B %d, %Y")
    pdf = PdfContent.objects.get(pk=pk)
    text = Pagetext.objects.get(pk=1)
    user_job_info = UserJobProfile.objects.get(user=request.user)
    user = request.user

    context = {
        "pdf": pdf,
        "text": text,
        "user": user,
        "company_name": pdf.cover_letter.company_name,
        "hiring_manager_info": pdf.cover_letter.content,
        "user_job_info": user_job_info,
        "date": date,
    }

    return render(request, "resumes/view_pdf_as_html.html", context)

templates/resumes/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Resume: {{resume.description}}</h2>
<strong>This is where you add the job description and other information about the job.
Below you will have a list of all job applications you have created. 
</strong>
</br></br> 
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      Hide Job Application Form
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <p>Show Job Application Form<small>  (create a new application)</small></p>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <p>Paste in the job description here.</p>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }} 
          {{ form.media }} 
          <button type="submit" class="btn btn-dark">Submit</button> 
        </form>
      </div>
    </div>
  </div>
</div>
<br>
<h3>Job Applications</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Created</th>
      <th scope="col">Number of Letters</th>
      <th scope="col">Resume</th>
      <th scope="col">Company</th>
      <th scope="col">Link to description</th>
      <th scope="col">Generate a Cover Letter Using AI</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for cov in cover  %}
    <tr>
      <th scope="row">{{ cov.time }}</th>
      <td>
        {{ cov.covers.all.count }}
      </td>
      <td>
        {{ resume.description }}
      </td>
      <td>{{ cov.company_name }}</td>
      <td>
        {% if cov.job_description_url %}
        <a href="{{ cov.job_description_url }}" 
          class="btn btn-outline-primary btn-sm" target="_blank">
        View URL
        </a>
        {% else %}
        No URL Provided
        {% endif %}
      </td>
      <td>
        <a href="{% url 'resumes:trigger_and_list' cov.id %}" 
          class="btn btn-outline-primary btn-sm">
        Create/View Letters
        </a>
      </td>
      <td>
        <a href="{% url 'resumes:delete_cover' cov.id %}" 
          class="btn btn-outline-danger btn-sm">Delete
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br><br><br><br><br>
{% endblock content %}

templates/resumes/index.html
{% extends 'base.html' %}
{% load static %} 
{% load crispy_forms_tags %}
{% block content%}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-7">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }} 
      <button type="submit">Upload</button> 
    </form>
  </div>
  <div class="col-md-4"></div>
</div>
<br>
<div class="row">
  <div class="col-md-4">
    <p>{{ text.url_link_description_4 }} <a href="{{text.url_4}}" target="_blank">
      <img src="{% static 'images/yt.svg' %}" alt="youtube logo" width="40">
      </a> 
    </p>
  </div>
  <div class="col-md-4">
  </div>
  <div class="col-md-4"></div>
</div>
<h2>Uploaded Resumes </h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Uploaded</th>
      <th scope="col"># of Job Profiles</th>
      <th scope="col"># Cover Letters Created</th>
      <th scope="col">Reseme Description</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for resume in resumes  %}
    <tr>
      <th scope="row">{{resume.uploaded_on }}</th>
      <td>
        {{resume.resumes.all.count }}
      </td>
      <td>
        {% for cover in resume.resumes.all%}
        {{cover.covers.all.count}}
        {% endfor %}
      </td>
      <td>{{resume.description|truncatewords:4}}</td>
      <td><a href="{% url 'resumes:create' resume.id %}" class="btn btn-outline-info btn-sm">Create/View Jobs</a></td>
      <td><a href="{{ resume.resume_path.url }}" class="btn btn-outline-primary btn-sm" target="_blank">View Resume</a></td>
      <td><a href="{% url 'resumes:delete' resume.id %}" class="btn btn-outline-danger btn-sm">Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br><br><br><br><br>
{% endblock content %}

templates/resumes/list_job_covers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Job Profiles</h2>
<table class="table">
    <thead>
      <tr>

        <th scope="col">Company</th>
        <th scope="col">Resume</th>
        <th scope="col">Letters Genereated</th>
        <th scope="col">Job URL</th>
        <th scope="col"></th>
        <th scope="col"></th>

      </tr>
    </thead>
    <tbody>
    
{% for cover in covers  %}
      <tr>
        <th scope="row">{{cover.company_name}}</th>
        <td>{{cover.resume_id.description}}</td>
        <td>{{cover.covers.all.count }}</td>

        <td>
            {% if cover.job_description_url %}
            <a target="_blank"  class= "btn btn-dark" href="{{ cover.job_description_url.url }}">Job Posting</a>
            {% else %}
            Not entered
            {% endif %}
        </td>
        <td><a class= "btn btn-dark" href="{% url 'resumes:update_description' cover.id %}">Edit Description</a></td>

        <td><a class= "btn btn-dark" href="{% url 'resumes:trigger_and_list' cover.id %}">View & Generate</a></td>

        
      </tr>
      {% endfor %}
    </tbody>
  </table>
  

{% if page_obj.has_other_pages %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Previous
                    </a>
                </li>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
                {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                    {% if page_obj.number == page_number %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">
                        Last
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
  {% endblock content %}

templates/resumes/trigger_and_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card text-center">
  <div style="position: relative;">
    <p style="position: absolute; left: 0; padding-top: 10px;">{{ cover.company_name }}</p>
    <p style="position: absolute; right: 0; padding-top: 10px;">{{ cover.resume_id.description }}</p>
  </div>
  <div class="card-header">
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ cover.company_name }}</h5>
    <form method="post" id="trigger_llm">
      <input type="hidden" name="form_type" value="trigger_llm">
      {% csrf_token %}
      <button class="btn btn-light btn-sm" type="submit">Generate Cover Letter</button> 
    </form>
  </div>
  <div class="card-footer text-muted">
    <a href="{% url 'resumes:update_description' cover.id %}"class="btn btn-dark btn-sm">
    Update Job Description
    </a>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Created</th>
      <th scope="col">Company</th>
      <th scope="col">(a list of all AI content for this Company)</th>
    </tr>
  </thead>
  <tbody>
    {% for pdf in pdfs  %}
    <tr>
      <th scope="row">{{pdf.time}}</th>
      <th scope="row">{{pdf.cover_letter.company_name}}</th>
      <td>
        <a href="{% url 'resumes:pdf_html' pdf.id %}" 
          class="btn btn-outline-primary btn-sm">
        View/Edit AI Content
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br><br><br><br><br><br>
{% endblock content %}

templates/resumes/view_pdf_as_html.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>{% if pdf.cover_letter.show_company_name_on_pdf %}{{ company_name }}{% endif %} </h1>

<div class="card">
  <div class="card-header">
    <div style="text-align: center;" class='header'>
      <a href="{% url 'resumes:user_job_profile_pdf' user.id pdf.id %}">Edit My Info</a>
      <br />
      <h1>
        {% if user.job_profile.show_my_name_on_pdf == True %}
        {{ user.job_profile.full_name }}
        {% endif %}
        </h1>
      {{ user.job_profile.content|safe}}
    </div>
  </div>
  <div class="card-body">
    <a href="{% url 'resumes:cover_address' pdf.cover_letter.id pdf.id %}"  >Edit Hiring Manager Info</a>
    <p class="card-title">
      {% if hiring_manager_info == None %}
      **Update Hiring Manager and Address**
      {% else %}
      {{ hiring_manager_info|safe }}
      {% endif %}
      
    </p>
    {{date}}
    <p class="card-text">{{ pdf.llm_text|safe }}</p>
    <a href="{% url 'resumes:edit_generated_text' pdf.id %}" class="btn btn-info">
    edit AI content
    </a>
  </div>
  <a href="{% url 'resumes:pdf_view' pdf.id %}" 
    class="btn btn-primary" target="_blank"> 
  View PDF
  </a>
  <a href="{% url 'resumes:pdf_download' pdf.id %}" 
  class="btn btn-dark" target="_blank"> 
Download PDF
</a>
</div>
{% endblock content %}