chats/urls.py
from django.urls import path
from chats.views import (
    IndexView,
    delete_view,
    chat_csv_view,
    chat_session_view,
    create_view,
    update_view,
)

app_name = "chats"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("csv/<int:pk>/", chat_csv_view, name="csv"),
    path("session/<int:pk>/", chat_session_view, name="chat"),
    path("create_with_file/", create_view, name="create"),
    path("update_with_file/<int:pk>/", update_view, name="update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('driver/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('documents/', include('documents.urls')),
    path('resumes/', include('resumes.urls')),
    path('chatter/', include('chats.urls')),
    path('urls/', include('urls.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

    

class Instruction(models.Model):
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, blank=False)
    prompt = models.TextField(blank=False, null=False)
    data = models.TextField(blank=False, null=False)
    time = models.DateTimeField(auto_now_add=True)
    data_text = models.FileField(upload_to="text_files/")
    class Meta:
        ordering = ('-time',)

    
class Chat(models.Model): 
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    instruction_id = models.ForeignKey(Instruction, related_name='chats', on_delete=models.CASCADE)
    model_used = models.CharField(max_length=700, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)
    input = models.TextField(blank=False, null=False)
    response = models.TextField(blank=True, null=True)
    class Meta:
        ordering = ('-time',)
    def __str__(self):
            return self.input

chats/forms.py
from chats.models import Instruction, Chat
from django import forms



class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        fields = ('description', 'prompt', 'data' )
        # widgets = {'document_url': forms.HiddenInput()}
        # def __init__(self, *args, **kwargs):
        #     super(DocumentForm, self).__init__(*args, **kwargs)
        #     self.fields['document_url'].initial = self.document_path

chats/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from chats.models import Instruction, Chat
from django.views.generic import ListView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pages.models import Profile, Pagetext
from chats.functions import chat_llm
from django.core.files.base import ContentFile
from chats.forms import InstructionForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from datetime import datetime
import csv

class IndexView(LoginRequiredMixin, ListView):
    model = Instruction
    fields = ["description", "prompt", "data"]
    context_object_name = "instructions"
    template_name = "chats/index.html"

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context["text"] = Pagetext.objects.get(pk=1)
        return context

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(user_id=self.request.user)




@login_required
def delete_view(request, pk):
    text = Pagetext.objects.get(pk=1)
    object = get_object_or_404(Instruction, id = pk)
    context ={"object" : object, "text" : text}
    if request.user != object.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method =="POST":
            object.delete()
            messages.add_message(request, messages.INFO, "Chatter deleted")
            return redirect("chats:index")
    
        return render(request, "chats/delete.html", context)
@login_required
def chat_session_view(request, pk):
    instructions = Instruction.objects.get(pk=pk)

    chats = Chat.objects.filter(instruction_id=pk)
    user = request.user
    profile = Profile.objects.get(user=user)
    # OPENAI_API_KEY = profile.open_api_key
    # print(f" ---- {profile.open_api_key}")
    data_file = request.build_absolute_uri(instructions.data_text.url)
    prompt = instructions.prompt
    text = Pagetext.objects.get(id=1)
    context = {
        "instructions": instructions,
        "chats": chats,
        "text": text,
    }
    if user != instructions.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if (
            request.method == "POST"
            or None
            and (
                request.POST.get("form_type") == "chatInteract"
                and request.POST.get("query")
            )
        ):
            query = request.POST.get("query")

            if query == "":
                messages.add_message(
                    request,
                    messages.INFO,
                    "You tried to send an empty query!  this is not allowed.",
                )
                return render(request, "chats/chat_session.html", context)
            else:
                # chat_llm(prompt=prompt, data_file_url=instructions.data_text.url, query=query, instruction_id=instructions, user=request.user)
                try:
                    chat_llm(
                        prompt=prompt,
                        data_file_url=instructions.data_text.path,
                        query=query,
                        instruction_id=instructions,
                        user=request.user,
                    )

                except Exception as e:
                    if e:
                        messages.add_message(
                            request,
                            messages.INFO,
                            "An empty response was returned.  check your API key",
                        )

                    else:
                        messages.add_message(
                            request,
                            messages.INFO,
                            "Try your request again, as there was a problem getting a response from the AI.",
                        )
                        return render(request, "chats/chat_session.html", context)

                return render(request, "chats/chat_session.html", context)

        return render(request, "chats/chat_session.html", context)


@login_required
def create_view(request):
    text = Pagetext.objects.get(id=1)

    form = InstructionForm(request.POST)

    if request.method == "POST":
        current_user = request.user
        if form.is_valid():
            wait_for_text = form.save(commit=False)
            file = ContentFile(
                wait_for_text.data,
                name=f"data_text_user{current_user.id}dt{datetime.now()}.txt",
            )
            wait_for_text.data_text = file
            wait_for_text.user_id = current_user
            wait_for_text.save()
            messages.add_message(request, messages.INFO, "Your Prompt has been saved.")
            return redirect("chats:index")
        else:
            messages.add_message(
                request, messages.INFO, "There was a problem saving your data."
            )
            return render(request, "chats/index.html", {"form": form, "text": text})

    return render(request, "chats/create.html", {"form": form, "text": text})


@login_required
def update_view(request, pk):
    instruction = Instruction.objects.get(pk=pk)
    chats = Chat.objects.filter(instruction_id=pk)

    form = InstructionForm(request.POST or None, instance=instruction)
    if request.user != instruction.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            current_user = request.user
            if form.is_valid():
                wait_for_text = form.save(commit=False)
                file = ContentFile(
                    wait_for_text.data,
                    name=f"data_text_user{current_user.id}dt{datetime.now()}.txt",
                )
                wait_for_text.data_text = file
                wait_for_text.user_id = current_user

                wait_for_text.save()
                messages.add_message(
                    request, messages.INFO, "LLM Instructions have been updated."
                )
                return redirect("chats:chat", instruction.id)
            else:
                messages.add_message(
                    request, messages.INFO, "There was a problem saving your data."
                )
                return render(
                    request, "chats/update.html", {"form": form, "instruction": instruction}
                )
        return render(
            request, "chats/update.html", {"form": form, "instruction": instruction}
        )

@login_required
def chat_csv_view(request, pk):
    instruction = Instruction.objects.get(pk=pk)
    chats = Chat.objects.filter(instruction_id=instruction)
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="chatter.csv"'},
    )
    website = "acmeai.io"
    email = "AI@acmeAI.io"
    writer = csv.writer(response)
    writer.writerow([f"Time", f"Input", "Response"])
    for data in chats:
        writer.writerow([f"{data.time}", f"{data.input}", f"{data.response}"])
    writer.writerow([])

    writer.writerow([f"#End of output#", f""])
    writer.writerow([f"File", f"Created On", f"Description"])
    writer.writerow(
        [
            f"{instruction.description}",
            f"{instruction.prompt}",
            f"{instruction.data}",
        ]
    )
    writer.writerow([])
    writer.writerow([])
    writer.writerow([f"##############", f""])
    writer.writerow([f"{email}", f"{website}"])
    return response

resumes/views/delete_view.py
from .libraries import *

@login_required
def delete_view(request, pk):
    text = Pagetext.objects.get(pk=1)
    object = get_object_or_404(Resume, id=pk)
    context = {"object": object, "text": text}
    if request.user != object.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            object.delete()
            messages.add_message(request, messages.INFO, "Resume deleted")
            return redirect("resumes:index")

        return render(request, "resumes/delete.html", context)
    

@login_required
def delete_cover_letter_view(request, pk):
    text = Pagetext.objects.get(pk=1)
    object = get_object_or_404(CoverLetter, id=pk)
   
    context = {"object": object, "text": text}
    if request.user != object.user_id:
        messages.add_message(request, messages.INFO, "Unauthorized Baby!")
        return redirect("/")
    else:
        if request.method == "POST":
            object.delete()
            messages.add_message(request, messages.INFO, "Cover Letter deleted")
            return redirect("resumes:create", object.resume_id.id)

        return render(request, "resumes/delete.html", context)

templates/chats/chat_session.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-md-4"><a href="{% url 'chats:index'%}" class="btn btn-light" role="button">Back</a></div>
  <div class="col-md-4"></div>
  <div class="col-md-4"><a href="{% url 'chats:update' instructions.id %}" class="btn btn-info" role="button">Update LLM Instuctions</a></div>
</div>
<br>
<br>
<div class='container'>{{ text.char_6 }} </div>
<br>

<div class="container bootstrap snippets bootdey">
  <div class="tile tile-alt" id="messages-main">
    <div class="ms-body">
      <div class="msb-reply">
        <form method=POST  id="chatInteract">
          <input type="hidden" name="form_type" value="chatInteract">
          {% csrf_token %}   
          <input type="text" name="query" class="form-control" id="query" placeholder="Query LLM">
          <button type="submit" ><i class="fa fa-paper-plane-o"></i></button>
        </form>
      </div>
      {% for chat in chats %}
      <div class="message-feed media">
        <div class="pull-left">
          <img src="{% static 'images/human.png' %}" alt="" class="img-avatar">
        </div>
        <div class="media-body">
          <div class="mf-content">
            {{ chat.input }}
          </div>
          <small class="mf-date"><i class="fa fa-clock-o"></i> {{ chat.time }}</small>
        </div>
      </div>
      <div class="message-feed right">
        <div class="pull-right"> 
          <img src="{% static 'images/robo.jpeg' %}" alt="" class="img-avatar">
        </div>
        <div class="media-body">
          <div class="mf-content">
            {{ chat.response }}                    
          </div>
          <small class="mf-date"><i class="fa fa-clock-o"></i> {{ chat.time }}</small>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

templates/chats/create.html
{% extends 'base.html' %}
{% block content%}
{% load static %}
{% load crispy_forms_tags %}

 


<div class="row">
  <div class="col-md-1"></div>


  <div class="col-md-7"><form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Save</button> 
  </form></div>
  <div class="col-md-4">
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Sample Desctiption
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            {{text.char_1|safe}}
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Sample Prompt
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            {{text.char_2|safe}}
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Sample Data
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            {{text.text_2|safe}}
          </div>
        </div>
      </div>
    </div>



  </div>
</div>

{% endblock content %}

templates/chats/delete.html
{% extends 'base.html' %}
{% block content%}
{% load crispy_forms_tags %}
<form method="POST">
  <!-- Security token by Django -->
  {% csrf_token %}
  <div class="card">
    <div class="card-header">
      You are deleting: "{{ object.description }}" 
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>Are you sure you want to delete this item and its related data?</p>
	<br/>
        <footer>    
          <input class="btn btn-danger" type="submit" value="Yes" />
          <a class="btn btn-info btn-sm ms-3" 
            href="{% url 'chats:index' %}"> Cancel </a>
        </footer>
      </blockquote>
    </div>
  </div>
</form>
{% endblock content %}

templates/chats/index.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
<p>{{ text.url_link_description_1 }} <a href="{{text.url_1}}" target="_blank">
  <img src="{% static 'images/yt.svg' %}" alt="youtube logo" width="40">
  </a> 
</p>
<a href="{% url 'chats:create' %}" class="btn btn-outline-info" role="button">Create Prompt</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Uploaded</th>
      <th scope="col"># of interactions</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for instruction in instructions  %}
    <tr>
      <th scope="row">{{instruction.time}}</th>
      <td>
        {%  if instruction.chats.all.count == 0 %}
        None
        {% else %}
        {{ instruction.chats.all.count }}
        {% endif %}
      </td>
      <td>{{instruction.description|truncatewords:5}}</td>
      <td>
        <a href="{% url 'chats:delete' instruction.id %}"class="btn btn-outline-danger btn-sm">Delete</a>
      </td>
      <td><a href="{% url 'chats:csv' instruction.id %}" class="btn btn-outline-primary btn-sm">Download Data</a></td>
      </td>
      <td><a href="{% url 'chats:update' instruction.id %}" class="btn btn-outline-secondary btn-sm">View|Update</a></td>
      <td><a href="{% url 'chats:chat' instruction.id %}"class="btn btn-outline-success btn-sm ms-3">Chat</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %} 

templates/chats/update.html
{% extends 'base.html' %}
{% block content%}
{% load crispy_forms_tags %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-7"><form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Update and return</button> 
  </form></div>
  <div class="col-md-4"></div>
</div>

{% endblock content %}