chats/urls.py
from django.urls import path
from chats.views import (
    IndexView,
    delete_view,
    chat_csv_view,
    chat_session_view,
    create_view,
    update_view,
)

app_name = "chats"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("csv/<int:pk>/", chat_csv_view, name="csv"),
    path("session/<int:pk>/", chat_session_view, name="chat"),
    path("create_with_file/", create_view, name="create"),
    path("update_with_file/<int:pk>/", update_view, name="update"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('driver/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
    path('documents/', include('documents.urls')),
    path('resumes/', include('resumes.urls')),
    path('chatter/', include('chats.urls')),
    path('urls/', include('urls.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import index_view, profile_view, private_view
app_name = 'pages'
urlpatterns = [
    path('private', private_view, name='private'),
    path('', index_view, name='index'),
    path('accounts/profile/<int:pk>/', profile_view, name='user_profile'),

]

resumes/urls.py
from django.urls import path
from .views.index import index_view
from .views.delete_view import delete_cover_letter_view, delete_view
from .views.trigger_llm_and_list import trigger_and_list_view
from .views.create_cover import create_cover_view
from .views.update_description import update_description_view
from .views.edit_generated_text import edit_generated_text_view
from .views.view_pdf_as_html import pdf_as_html_view
from .views.view_pdf import pdf_view, pdf_download
from .views.user_job_profile import (
    user_job_profile_view,
    user_job_profile_pdf_view,
    user_job_profile_form_view
)
from .views.edit_cover_address_to import cover_address_view
from.views.list_job_covers import ListJobCovers


app_name = "resumes"

urlpatterns = [
    path("index/", index_view, name="index"),
    path("create/<int:pk>/", create_cover_view, name="create"),
    path("llm-and-list/<int:pk>/", trigger_and_list_view, name="trigger_and_list"),
    path(
        "update-description/<int:pk>/",
        update_description_view,
        name="update_description",
    ),
    path(
        "edit-generated-text/<int:pk>/",
        edit_generated_text_view,
        name="edit_generated_text",
    ),
    path("pdf-html/<int:pk>/", pdf_as_html_view, name="pdf_html"),
    path("cover-pdf/<int:pk>/", pdf_view, name="pdf_view"),
    path("download-pdf/<int:pk>/", pdf_download, name="pdf_download"),
    path("user-job-profile/<int:pk>/", user_job_profile_view, name="user_job_profile"),
    path("user-job-profile-form/<int:pk>/", user_job_profile_form_view, name="user_job_profile_form"),
    path("job-covers/<int:pk>/", ListJobCovers.as_view(), name="list_job_covers") ,
 
    path(
        "user-job-profile-pdf/<int:pk>/<int:id>/",
        user_job_profile_pdf_view,
        name="user_job_profile_pdf",
    ),
    path(
        "cover-address/<int:pk>/<int:pdf_key>/",
        cover_address_view,
        name="cover_address",
    ),
    path("delete/<int:pk>/", delete_view, name="delete"),
    path("delete-cover/<int:pk>/", delete_cover_letter_view, name="delete_cover"),
]

urls/urls.py
from django.urls import path
from urls.views import url_index_view, interaction_view, delete_view, url_csv_view

app_name='urls'
urlpatterns = [
    path('', url_index_view, name='index'),
    path('interactions/<int:pk>/', interaction_view, name='interactions'),

    path('csv/<int:pk>/', url_csv_view, name='csv'),
    path('delete/<int:pk>/', delete_view, name='delete'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>acmeAI</title>
   <script src="https://cdn.ckeditor.com/ckeditor5/38.1.1/classic/ckeditor.js"></script>
    <link rel="icon" type="image/x-icon" href="{% static '/images/favicons/favicon-32x32.png' %}"> 
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
  </head>
  <body>
    {% include "navigation.html" %}
    <div class="container">
      <div class="mt-5 mb-5">
        {% include "messages.html" %}
        {% block content %}{% endblock content %}
      </div>
    </div>
    {% include 'footer.html' %}
  </body>
<script src="{% static 'js/bootstrap.js' %}" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="{% static 'js/js.js' %}" ></script>
  <script src="{% static 'ckeditor/ckeditor-init.js' %}" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
</html>

templates/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <div class="col-md-4 d-flex align-items-center">
    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
    </a>
    <span class="mb-3 mb-md-0 text-muted">&copy; {% now "Y" %} acmeAI</span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
    <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
    <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
    <li class="ms-3"><span class="text-muted" href="">Made with ❤️ using Python<svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></span></li>
  </ul>
</footer> 


      

templates/messages.html
{% if messages %}

{% for message in messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %} 
{% endif %}

templates/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'pages:index' %}"> 
    <img src="{% static '/images/logoround.png'%}" width="130" height="50" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        {% if user.is_authenticated %} 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Interact with...
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'documents:index' %}">Documents</a></li>
            <li><a class="dropdown-item" href="{% url 'urls:index' %}">Urls</a></li>
            <li><a class="dropdown-item" href="{% url 'chats:index' %}">Chat Bots</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Resume Covers
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="nav-item"><a class="nav-link" href="{% url 'resumes:index' %}">Upload Resumes</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'resumes:list_job_covers' user.id %}">Created Jobs</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'resumes:user_job_profile_form' user.id %}">My Cover Info</a></li>
          </ul>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'pages:user_profile' user.profile.id %}">Profile</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Log Out</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'pages:private' %}">Private Data</a></li>
        {% endif %} 
        {% if not user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'pages:private' %}">Private Data</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>